CONDA_INC = C:\Users\WilliamHampshire\miniconda3\envs\mkl-cpp-build\Library\include
CONDA_LIB = C:\Users\WilliamHampshire\miniconda3\envs\mkl-cpp-build\Library\lib

# use mkl instead of openblas, cholmod, lapack separately - good compat for msvc
BLAS_LIB = mkl_rt.lib
LAPACK_LIB = mkl_rt.lib
FFTW3_LIB = mkl_rt.lib
CHOLMOD_LIBS = cholmod.lib amd.lib colamd.lib camd.lib ccolamd.lib suitesparseconfig.lib metis.lib
BOOST_LIB = boost_serialization.lib libboost_exception.lib

INCLUDES = /I. /IS4 /IS4\RNP /IS4\kiss_fft /IS4\fmm /IS4\pattern /I$(CONDA_INC) /I$(CONDA_INC)\suitesparse /I$(CONDA_INC)\fftw /DBOOST_ALL_NO_LIB
LIBPATHS = /LIBPATH:$(CONDA_LIB)

CPPFLAGS = /nologo /O2 /MD /W4 /EHsc /DWIN32 $(INCLUDES) /DENABLE_S4_TRACE
CFLAGS = $(CPPFLAGS)

# compiler msvc
CXX = cl
CC  = cl

OBJDIR = $(SRC_DIR)\conda_recipe\s4\build
S4_LIBNAME = $(OBJDIR)\libS4.lib

ALL_OBJS = \
    $(OBJDIR)\S4k\S4.obj \
    $(OBJDIR)\S4k\rcwa.obj \
    $(OBJDIR)\S4k\fmm_common.obj \
    $(OBJDIR)\S4k\fmm_FFT.obj \
    $(OBJDIR)\S4k\fmm_kottke.obj \
    $(OBJDIR)\S4k\fmm_closed.obj \
    $(OBJDIR)\S4k\fmm_PolBasisNV.obj \
    $(OBJDIR)\S4k\fmm_PolBasisVL.obj \
    $(OBJDIR)\S4k\fmm_PolBasisJones.obj \
    $(OBJDIR)\S4k\fmm_experimental.obj \
    $(OBJDIR)\S4k\fft_iface.obj \
    $(OBJDIR)\S4k\pattern.obj \
    $(OBJDIR)\S4k\intersection.obj \
    $(OBJDIR)\S4k\predicates.obj \
    $(OBJDIR)\S4k\numalloc.obj \
    $(OBJDIR)\S4k\gsel.obj \
    $(OBJDIR)\S4k\sort.obj \
    $(OBJDIR)\S4k\kiss_fft.obj \
    $(OBJDIR)\S4k\kiss_fftnd.obj \
    $(OBJDIR)\S4k\SpectrumSampler.obj \
    $(OBJDIR)\S4k\cubature.obj \
    $(OBJDIR)\S4k\Interpolator.obj \
    $(OBJDIR)\S4k\convert.obj \
    $(OBJDIR)\S4k\Eigensystems.obj

all: dirs $(S4_LIBNAME)

dirs:
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	if exist $(OBJDIR) if not exist $(OBJDIR)\S4k mkdir $(OBJDIR)\S4k

$(S4_LIBNAME): $(ALL_OBJS)
	lib /OUT:$@ $(ALL_OBJS) $(LIBPATHS) $(BLAS_LIB) $(LAPACK_LIB) $(FFTW3_LIB) $(CHOLMOD_LIBS) $(BOOST_LIB)


# --- Compilation rules ---

$(OBJDIR)\S4k\S4.obj: S4\S4.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\rcwa.obj: S4\rcwa.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_common.obj: S4\fmm\fmm_common.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_FFT.obj: S4\fmm\fmm_FFT.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_kottke.obj: S4\fmm\fmm_kottke.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_closed.obj: S4\fmm\fmm_closed.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_PolBasisNV.obj: S4\fmm\fmm_PolBasisNV.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_PolBasisVL.obj: S4\fmm\fmm_PolBasisVL.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_PolBasisJones.obj: S4\fmm\fmm_PolBasisJones.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fmm_experimental.obj: S4\fmm\fmm_experimental.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\fft_iface.obj: S4\fmm\fft_iface.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\pattern.obj: S4\pattern\pattern.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\intersection.obj: S4\pattern\intersection.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\predicates.obj: S4\pattern\predicates.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\numalloc.obj: S4\numalloc.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\gsel.obj: S4\gsel.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\sort.obj: S4\sort.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\kiss_fft.obj: S4\kiss_fft\kiss_fft.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\kiss_fftnd.obj: S4\kiss_fft\tools\kiss_fftnd.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\SpectrumSampler.obj: S4\SpectrumSampler.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\cubature.obj: S4\cubature.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\Interpolator.obj: S4\Interpolator.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\convert.obj: S4\convert.c
	$(CC) /c $(CFLAGS) /Fo$@ $**

$(OBJDIR)\S4k\Eigensystems.obj: S4\RNP\Eigensystems.cpp
	$(CXX) /c $(CPPFLAGS) /Fo$@ $**
