package:
  name: s4
  version: 1.1

source:
  path: ../../

build:
  number: 0
  script: |
    # .env vars (abs paths)
    export SRC_DIR="$SRC_DIR"
    export OBJDIR="$SRC_DIR/conda_recipe/s4/build"
    export CONDA_INC="$BUILD_PREFIX/include"
    export CONDA_LIB="$BUILD_PREFIX/lib"
    export NUMPY_INCLUDE=$(python -c "import numpy; print(numpy.get_include())")

    # Build the static library, exectuing from SRC_DIR (IMPORTANT)
    make -C $SRC_DIR -f conda_recipe/s4/Makefile all
    
    # Copy libS4.a into conda build dir
    cp "$SRC_DIR/build/libS4.a" "$SRC_DIR/conda_recipe/s4/"

    # Build and install the wheel
    $PYTHON -m pip wheel "$SRC_DIR/conda_recipe/s4" -w dist
    $PYTHON -m pip install dist/*.whl --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - wheel
    - boost
    - suitesparse
    - mkl-devel [win]
    - openblas [unix]

  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - wheel
    - boost
    - suitesparse
    - mkl-devel # [win]
    - openblas # [unix]

  run:
    - {{ pin_compatible('python') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('suitesparse') }}
    - {{ pin_compatible('mkl') }} # [win]
    - {{ pin_compatible('openblas') }} # [unix]

test:
  imports:
    - S4

about:
  home: https://web.stanford.edu/group/fan/S4/index.html
  license: GPL-2.0
  license_family: GPL
  # license_file: LICENSE.txt
  summary: 'S4 (Stanford Stratified Structure Solver) Conda Package'

  # The remaining entries in this section are optional, but recommended.
  description: |
    Forked https://github.com/willhampshire/S4 from https://github.com/paulgoulain/S4:
    
    These are conda packages of the below software. 
    Victor Liu wrote the initial code but is not responsible for these packages.
    A program for computing electromagnetic fields in periodic, layered
    structures, developed by Victor Liu (victorliu@alumni.stanford.edu) of the
    Fan group in the Stanford Electrical Engineering Department.
    See the S4 manual, in doc/index.html, for a complete
    description of the package and its user interface, as well as
    installation instructions, the license and copyright, contact
    addresses, and other important information.
    
    Modified to build using Python 3.10 to 3.12, with NumPy 1.26 (max supported by conda currently).
    Repaired errors generated during build in C source files.
    Replaced dependencies throwing errors (libboost).
    Rewrote build configuration to PEP 517/518; kept modified Makefile and meta.yaml, 
    created setup.cfg, setup.py (no gensetup.py.sh), pyproject.toml. 
    All other files in recipe are redundant and may interfere with build so are deleted.

  doc_url: https://web.stanford.edu/group/fan/S4/index.html
  dev_url: https://web.stanford.edu/group/fan/S4/index.html

