[metadata]
name = s4
version = 1.1
description = Stanford Stratified Structure Solver (S4)
python_requires = >=3.10,<3.13
zip_safe = false

[options]
packages = find:
include_package_data = true
install_requires =
    numpy
    boost
    suitesparse
    mkl ; sys_platform == "win32"
    openblas ; sys_platform != "win32"

[options.package_data]
* = libS4.a