var annotated_dup =
[
    [ "RNP", "namespace_r_n_p.html", [
      [ "IO", "namespace_r_n_p_1_1_i_o.html", [
        [ "_NumberOutputter", "class_r_n_p_1_1_i_o_1_1___number_outputter.html", "class_r_n_p_1_1_i_o_1_1___number_outputter" ],
        [ "_NumberOutputter< std::complex< T > >", "class_r_n_p_1_1_i_o_1_1___number_outputter_3_01std_1_1complex_3_01_t_01_4_01_4.html", "class_r_n_p_1_1_i_o_1_1___number_outputter_3_01std_1_1complex_3_01_t_01_4_01_4" ]
      ] ],
      [ "TBLAS", "namespace_r_n_p_1_1_t_b_l_a_s.html", [
        [ "_RealOrComplexChooser", "struct_r_n_p_1_1_t_b_l_a_s_1_1___real_or_complex_chooser.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1___real_or_complex_chooser" ],
        [ "_RealOrComplexChooser< std::complex< T > >", "struct_r_n_p_1_1_t_b_l_a_s_1_1___real_or_complex_chooser_3_01std_1_1complex_3_01_t_01_4_01_4.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1___real_or_complex_chooser_3_01std_1_1complex_3_01_t_01_4_01_4" ],
        [ "CopyMatrix", "struct_r_n_p_1_1_t_b_l_a_s_1_1_copy_matrix.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_copy_matrix" ],
        [ "MultHermV", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_herm_v.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_herm_v" ],
        [ "MultMM", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_m_m.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_m_m" ],
        [ "MultMV", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_m_v.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_m_v" ],
        [ "MultTrM", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_tr_m.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_tr_m" ],
        [ "MultTrV", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_tr_v.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_mult_tr_v" ],
        [ "SetMatrix", "struct_r_n_p_1_1_t_b_l_a_s_1_1_set_matrix.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_set_matrix" ],
        [ "SolveTrM", "struct_r_n_p_1_1_t_b_l_a_s_1_1_solve_tr_m.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_solve_tr_m" ],
        [ "SolveTrV", "struct_r_n_p_1_1_t_b_l_a_s_1_1_solve_tr_v.html", "struct_r_n_p_1_1_t_b_l_a_s_1_1_solve_tr_v" ]
      ] ],
      [ "TLASupport", "namespace_r_n_p_1_1_t_l_a_support.html", [
        [ "ApplyElementaryReflector", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_elementary_reflector.html", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_elementary_reflector" ],
        [ "ApplyElementaryReflectorBlocked", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_elementary_reflector_blocked.html", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_elementary_reflector_blocked" ],
        [ "ApplyOrthognalMatrixFromElementaryReflectors", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_orthognal_matrix_from_elementary_reflectors.html", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_orthognal_matrix_from_elementary_reflectors" ],
        [ "ApplyPermutations", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_permutations.html", "struct_r_n_p_1_1_t_l_a_support_1_1_apply_permutations" ],
        [ "CheapHessenbergNorm", "struct_r_n_p_1_1_t_l_a_support_1_1_cheap_hessenberg_norm.html", "struct_r_n_p_1_1_t_l_a_support_1_1_cheap_hessenberg_norm" ],
        [ "CheapMatrixNorm", "struct_r_n_p_1_1_t_l_a_support_1_1_cheap_matrix_norm.html", "struct_r_n_p_1_1_t_l_a_support_1_1_cheap_matrix_norm" ],
        [ "GeneralizedHessenbergReduction", "struct_r_n_p_1_1_t_l_a_support_1_1_generalized_hessenberg_reduction.html", "struct_r_n_p_1_1_t_l_a_support_1_1_generalized_hessenberg_reduction" ],
        [ "LUSolve", "struct_r_n_p_1_1_t_l_a_support_1_1_l_u_solve.html", "struct_r_n_p_1_1_t_l_a_support_1_1_l_u_solve" ],
        [ "RescaleMatrix", "struct_r_n_p_1_1_t_l_a_support_1_1_rescale_matrix.html", "struct_r_n_p_1_1_t_l_a_support_1_1_rescale_matrix" ]
      ] ],
      [ "LinearSolve", "struct_r_n_p_1_1_linear_solve.html", "struct_r_n_p_1_1_linear_solve" ]
    ] ],
    [ "cached_fft", "structcached__fft.html", "structcached__fft" ],
    [ "data_point_", "structdata__point__.html", "structdata__point__" ],
    [ "epsilon_converter_data", "structepsilon__converter__data.html", "structepsilon__converter__data" ],
    [ "esterr", "structesterr.html", "structesterr" ],
    [ "Excitation_", "struct_excitation__.html", "struct_excitation__" ],
    [ "Excitation_Dipole_", "struct_excitation___dipole__.html", "struct_excitation___dipole__" ],
    [ "Excitation_Exterior_", "struct_excitation___exterior__.html", "struct_excitation___exterior__" ],
    [ "Excitation_Planewave_", "struct_excitation___planewave__.html", "struct_excitation___planewave__" ],
    [ "FieldCache", "struct_field_cache.html", "struct_field_cache" ],
    [ "fv_data_s", "structfv__data__s.html", "structfv__data__s" ],
    [ "heap", "structheap.html", "structheap" ],
    [ "hypercube", "structhypercube.html", "structhypercube" ],
    [ "IntegrateFunction_data", "struct_integrate_function__data.html", "struct_integrate_function__data" ],
    [ "Interpolator_", "struct_interpolator__.html", "struct_interpolator__" ],
    [ "kiss_fft_cpx", "structkiss__fft__cpx.html", "structkiss__fft__cpx" ],
    [ "kiss_fft_state", "structkiss__fft__state.html", "structkiss__fft__state" ],
    [ "kiss_fftnd_state", "structkiss__fftnd__state.html", "structkiss__fftnd__state" ],
    [ "kiss_fftndr_state", "structkiss__fftndr__state.html", "structkiss__fftndr__state" ],
    [ "kiss_fftr_state", "structkiss__fftr__state.html", "structkiss__fftr__state" ],
    [ "lanczos_smoothing_settings", "structlanczos__smoothing__settings.html", "structlanczos__smoothing__settings" ],
    [ "Layer_", "struct_layer__.html", "struct_layer__" ],
    [ "LayerBands", "struct_layer_bands.html", "struct_layer_bands" ],
    [ "LayerSolution", "struct_layer_solution.html", "struct_layer_solution" ],
    [ "Material_", "struct_material__.html", "struct_material__" ],
    [ "module_state", "structmodule__state.html", "structmodule__state" ],
    [ "Options_", "struct_options__.html", "struct_options__" ],
    [ "ParallelInvokeData", "struct_parallel_invoke_data.html", "struct_parallel_invoke_data" ],
    [ "Pattern_", "struct_pattern__.html", "struct_pattern__" ],
    [ "polygon_converter_data", "structpolygon__converter__data.html", "structpolygon__converter__data" ],
    [ "region", "structregion.html", "structregion" ],
    [ "rgb_t", "structrgb__t.html", "structrgb__t" ],
    [ "rule75genzmalik", "structrule75genzmalik.html", "structrule75genzmalik" ],
    [ "rule_s", "structrule__s.html", "structrule__s" ],
    [ "S4_solve_in_parallel_data_", "struct_s4__solve__in__parallel__data__.html", "struct_s4__solve__in__parallel__data__" ],
    [ "S4Excitation_Data", "struct_s4_excitation___data.html", "struct_s4_excitation___data" ],
    [ "S4Interpolator", "struct_s4_interpolator.html", "struct_s4_interpolator" ],
    [ "S4Interpolator_Data", "struct_s4_interpolator___data.html", "struct_s4_interpolator___data" ],
    [ "S4Sim", "struct_s4_sim.html", "struct_s4_sim" ],
    [ "S4SpectrumSampler", "struct_s4_spectrum_sampler.html", "struct_s4_spectrum_sampler" ],
    [ "S4SpectrumSampler_Data", "struct_s4_spectrum_sampler___data.html", "struct_s4_spectrum_sampler___data" ],
    [ "shape_", "structshape__.html", "structshape__" ],
    [ "Simulation_", "struct_simulation__.html", "struct_simulation__" ],
    [ "Solution_", "struct_solution__.html", "struct_solution__" ],
    [ "SolveTrV_Scaled", "struct_solve_tr_v___scaled.html", "struct_solve_tr_v___scaled" ],
    [ "SpectrumSampler_", "struct_spectrum_sampler__.html", "struct_spectrum_sampler__" ],
    [ "SpectrumSampler_Options", "struct_spectrum_sampler___options.html", "struct_spectrum_sampler___options" ],
    [ "stack_node", "structstack__node.html", "structstack__node" ],
    [ "tag_fft_plan", "structtag__fft__plan.html", "structtag__fft__plan" ]
];